require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdeudosController do

  # This should return the minimal set of attributes required to create a valid
  # Adeudo. As you add validations to Adeudo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "numero_libros" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdeudosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all adeudos as @adeudos" do
      adeudo = Adeudo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adeudos).should eq([adeudo])
    end
  end

  describe "GET show" do
    it "assigns the requested adeudo as @adeudo" do
      adeudo = Adeudo.create! valid_attributes
      get :show, {:id => adeudo.to_param}, valid_session
      assigns(:adeudo).should eq(adeudo)
    end
  end

  describe "GET new" do
    it "assigns a new adeudo as @adeudo" do
      get :new, {}, valid_session
      assigns(:adeudo).should be_a_new(Adeudo)
    end
  end

  describe "GET edit" do
    it "assigns the requested adeudo as @adeudo" do
      adeudo = Adeudo.create! valid_attributes
      get :edit, {:id => adeudo.to_param}, valid_session
      assigns(:adeudo).should eq(adeudo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Adeudo" do
        expect {
          post :create, {:adeudo => valid_attributes}, valid_session
        }.to change(Adeudo, :count).by(1)
      end

      it "assigns a newly created adeudo as @adeudo" do
        post :create, {:adeudo => valid_attributes}, valid_session
        assigns(:adeudo).should be_a(Adeudo)
        assigns(:adeudo).should be_persisted
      end

      it "redirects to the created adeudo" do
        post :create, {:adeudo => valid_attributes}, valid_session
        response.should redirect_to(Adeudo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adeudo as @adeudo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adeudo.any_instance.stub(:save).and_return(false)
        post :create, {:adeudo => { "numero_libros" => "invalid value" }}, valid_session
        assigns(:adeudo).should be_a_new(Adeudo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adeudo.any_instance.stub(:save).and_return(false)
        post :create, {:adeudo => { "numero_libros" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adeudo" do
        adeudo = Adeudo.create! valid_attributes
        # Assuming there are no other adeudos in the database, this
        # specifies that the Adeudo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Adeudo.any_instance.should_receive(:update).with({ "numero_libros" => "1" })
        put :update, {:id => adeudo.to_param, :adeudo => { "numero_libros" => "1" }}, valid_session
      end

      it "assigns the requested adeudo as @adeudo" do
        adeudo = Adeudo.create! valid_attributes
        put :update, {:id => adeudo.to_param, :adeudo => valid_attributes}, valid_session
        assigns(:adeudo).should eq(adeudo)
      end

      it "redirects to the adeudo" do
        adeudo = Adeudo.create! valid_attributes
        put :update, {:id => adeudo.to_param, :adeudo => valid_attributes}, valid_session
        response.should redirect_to(adeudo)
      end
    end

    describe "with invalid params" do
      it "assigns the adeudo as @adeudo" do
        adeudo = Adeudo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adeudo.any_instance.stub(:save).and_return(false)
        put :update, {:id => adeudo.to_param, :adeudo => { "numero_libros" => "invalid value" }}, valid_session
        assigns(:adeudo).should eq(adeudo)
      end

      it "re-renders the 'edit' template" do
        adeudo = Adeudo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adeudo.any_instance.stub(:save).and_return(false)
        put :update, {:id => adeudo.to_param, :adeudo => { "numero_libros" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adeudo" do
      adeudo = Adeudo.create! valid_attributes
      expect {
        delete :destroy, {:id => adeudo.to_param}, valid_session
      }.to change(Adeudo, :count).by(-1)
    end

    it "redirects to the adeudos list" do
      adeudo = Adeudo.create! valid_attributes
      delete :destroy, {:id => adeudo.to_param}, valid_session
      response.should redirect_to(adeudos_url)
    end
  end

end
