require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AsistenciasController do

  # This should return the minimal set of attributes required to create a valid
  # Asistencias. As you add validations to Asistencias, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "presente" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AsistenciasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all asistencias as @asistencias" do
      asistencias = Asistencias.create! valid_attributes
      get :index, {}, valid_session
      assigns(:asistencias).should eq([asistencias])
    end
  end

  describe "GET show" do
    it "assigns the requested asistencias as @asistencias" do
      asistencias = Asistencias.create! valid_attributes
      get :show, {:id => asistencias.to_param}, valid_session
      assigns(:asistencias).should eq(asistencias)
    end
  end

  describe "GET new" do
    it "assigns a new asistencias as @asistencias" do
      get :new, {}, valid_session
      assigns(:asistencias).should be_a_new(Asistencias)
    end
  end

  describe "GET edit" do
    it "assigns the requested asistencias as @asistencias" do
      asistencias = Asistencias.create! valid_attributes
      get :edit, {:id => asistencias.to_param}, valid_session
      assigns(:asistencias).should eq(asistencias)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Asistencias" do
        expect {
          post :create, {:asistencias => valid_attributes}, valid_session
        }.to change(Asistencias, :count).by(1)
      end

      it "assigns a newly created asistencias as @asistencias" do
        post :create, {:asistencias => valid_attributes}, valid_session
        assigns(:asistencias).should be_a(Asistencias)
        assigns(:asistencias).should be_persisted
      end

      it "redirects to the created asistencias" do
        post :create, {:asistencias => valid_attributes}, valid_session
        response.should redirect_to(Asistencias.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved asistencias as @asistencias" do
        # Trigger the behavior that occurs when invalid params are submitted
        Asistencias.any_instance.stub(:save).and_return(false)
        post :create, {:asistencias => { "presente" => "invalid value" }}, valid_session
        assigns(:asistencias).should be_a_new(Asistencias)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Asistencias.any_instance.stub(:save).and_return(false)
        post :create, {:asistencias => { "presente" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested asistencias" do
        asistencias = Asistencias.create! valid_attributes
        # Assuming there are no other asistencias in the database, this
        # specifies that the Asistencias created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Asistencias.any_instance.should_receive(:update).with({ "presente" => "false" })
        put :update, {:id => asistencias.to_param, :asistencias => { "presente" => "false" }}, valid_session
      end

      it "assigns the requested asistencias as @asistencias" do
        asistencias = Asistencias.create! valid_attributes
        put :update, {:id => asistencias.to_param, :asistencias => valid_attributes}, valid_session
        assigns(:asistencias).should eq(asistencias)
      end

      it "redirects to the asistencias" do
        asistencias = Asistencias.create! valid_attributes
        put :update, {:id => asistencias.to_param, :asistencias => valid_attributes}, valid_session
        response.should redirect_to(asistencias)
      end
    end

    describe "with invalid params" do
      it "assigns the asistencias as @asistencias" do
        asistencias = Asistencias.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Asistencias.any_instance.stub(:save).and_return(false)
        put :update, {:id => asistencias.to_param, :asistencias => { "presente" => "invalid value" }}, valid_session
        assigns(:asistencias).should eq(asistencias)
      end

      it "re-renders the 'edit' template" do
        asistencias = Asistencias.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Asistencias.any_instance.stub(:save).and_return(false)
        put :update, {:id => asistencias.to_param, :asistencias => { "presente" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested asistencias" do
      asistencias = Asistencias.create! valid_attributes
      expect {
        delete :destroy, {:id => asistencias.to_param}, valid_session
      }.to change(Asistencias, :count).by(-1)
    end

    it "redirects to the asistencias list" do
      asistencias = Asistencias.create! valid_attributes
      delete :destroy, {:id => asistencias.to_param}, valid_session
      response.should redirect_to(asistencias_index_url)
    end
  end

end
