require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CriteriosController do

  # This should return the minimal set of attributes required to create a valid
  # Criterio. As you add validations to Criterio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CriteriosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all criterios as @criterios" do
      criterio = Criterio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:criterios).should eq([criterio])
    end
  end

  describe "GET show" do
    it "assigns the requested criterio as @criterio" do
      criterio = Criterio.create! valid_attributes
      get :show, {:id => criterio.to_param}, valid_session
      assigns(:criterio).should eq(criterio)
    end
  end

  describe "GET new" do
    it "assigns a new criterio as @criterio" do
      get :new, {}, valid_session
      assigns(:criterio).should be_a_new(Criterio)
    end
  end

  describe "GET edit" do
    it "assigns the requested criterio as @criterio" do
      criterio = Criterio.create! valid_attributes
      get :edit, {:id => criterio.to_param}, valid_session
      assigns(:criterio).should eq(criterio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Criterio" do
        expect {
          post :create, {:criterio => valid_attributes}, valid_session
        }.to change(Criterio, :count).by(1)
      end

      it "assigns a newly created criterio as @criterio" do
        post :create, {:criterio => valid_attributes}, valid_session
        assigns(:criterio).should be_a(Criterio)
        assigns(:criterio).should be_persisted
      end

      it "redirects to the created criterio" do
        post :create, {:criterio => valid_attributes}, valid_session
        response.should redirect_to(Criterio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved criterio as @criterio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Criterio.any_instance.stub(:save).and_return(false)
        post :create, {:criterio => {  }}, valid_session
        assigns(:criterio).should be_a_new(Criterio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Criterio.any_instance.stub(:save).and_return(false)
        post :create, {:criterio => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested criterio" do
        criterio = Criterio.create! valid_attributes
        # Assuming there are no other criterios in the database, this
        # specifies that the Criterio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Criterio.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => criterio.to_param, :criterio => { "these" => "params" }}, valid_session
      end

      it "assigns the requested criterio as @criterio" do
        criterio = Criterio.create! valid_attributes
        put :update, {:id => criterio.to_param, :criterio => valid_attributes}, valid_session
        assigns(:criterio).should eq(criterio)
      end

      it "redirects to the criterio" do
        criterio = Criterio.create! valid_attributes
        put :update, {:id => criterio.to_param, :criterio => valid_attributes}, valid_session
        response.should redirect_to(criterio)
      end
    end

    describe "with invalid params" do
      it "assigns the criterio as @criterio" do
        criterio = Criterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Criterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => criterio.to_param, :criterio => {  }}, valid_session
        assigns(:criterio).should eq(criterio)
      end

      it "re-renders the 'edit' template" do
        criterio = Criterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Criterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => criterio.to_param, :criterio => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested criterio" do
      criterio = Criterio.create! valid_attributes
      expect {
        delete :destroy, {:id => criterio.to_param}, valid_session
      }.to change(Criterio, :count).by(-1)
    end

    it "redirects to the criterios list" do
      criterio = Criterio.create! valid_attributes
      delete :destroy, {:id => criterio.to_param}, valid_session
      response.should redirect_to(criterios_url)
    end
  end

end
