require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CuatrimestresController do

  # This should return the minimal set of attributes required to create a valid
  # Cuatrimestre. As you add validations to Cuatrimestre, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CuatrimestresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cuatrimestres as @cuatrimestres" do
      cuatrimestre = Cuatrimestre.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cuatrimestres).should eq([cuatrimestre])
    end
  end

  describe "GET show" do
    it "assigns the requested cuatrimestre as @cuatrimestre" do
      cuatrimestre = Cuatrimestre.create! valid_attributes
      get :show, {:id => cuatrimestre.to_param}, valid_session
      assigns(:cuatrimestre).should eq(cuatrimestre)
    end
  end

  describe "GET new" do
    it "assigns a new cuatrimestre as @cuatrimestre" do
      get :new, {}, valid_session
      assigns(:cuatrimestre).should be_a_new(Cuatrimestre)
    end
  end

  describe "GET edit" do
    it "assigns the requested cuatrimestre as @cuatrimestre" do
      cuatrimestre = Cuatrimestre.create! valid_attributes
      get :edit, {:id => cuatrimestre.to_param}, valid_session
      assigns(:cuatrimestre).should eq(cuatrimestre)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cuatrimestre" do
        expect {
          post :create, {:cuatrimestre => valid_attributes}, valid_session
        }.to change(Cuatrimestre, :count).by(1)
      end

      it "assigns a newly created cuatrimestre as @cuatrimestre" do
        post :create, {:cuatrimestre => valid_attributes}, valid_session
        assigns(:cuatrimestre).should be_a(Cuatrimestre)
        assigns(:cuatrimestre).should be_persisted
      end

      it "redirects to the created cuatrimestre" do
        post :create, {:cuatrimestre => valid_attributes}, valid_session
        response.should redirect_to(Cuatrimestre.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cuatrimestre as @cuatrimestre" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cuatrimestre.any_instance.stub(:save).and_return(false)
        post :create, {:cuatrimestre => { "nombre" => "invalid value" }}, valid_session
        assigns(:cuatrimestre).should be_a_new(Cuatrimestre)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cuatrimestre.any_instance.stub(:save).and_return(false)
        post :create, {:cuatrimestre => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cuatrimestre" do
        cuatrimestre = Cuatrimestre.create! valid_attributes
        # Assuming there are no other cuatrimestres in the database, this
        # specifies that the Cuatrimestre created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cuatrimestre.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => cuatrimestre.to_param, :cuatrimestre => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested cuatrimestre as @cuatrimestre" do
        cuatrimestre = Cuatrimestre.create! valid_attributes
        put :update, {:id => cuatrimestre.to_param, :cuatrimestre => valid_attributes}, valid_session
        assigns(:cuatrimestre).should eq(cuatrimestre)
      end

      it "redirects to the cuatrimestre" do
        cuatrimestre = Cuatrimestre.create! valid_attributes
        put :update, {:id => cuatrimestre.to_param, :cuatrimestre => valid_attributes}, valid_session
        response.should redirect_to(cuatrimestre)
      end
    end

    describe "with invalid params" do
      it "assigns the cuatrimestre as @cuatrimestre" do
        cuatrimestre = Cuatrimestre.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cuatrimestre.any_instance.stub(:save).and_return(false)
        put :update, {:id => cuatrimestre.to_param, :cuatrimestre => { "nombre" => "invalid value" }}, valid_session
        assigns(:cuatrimestre).should eq(cuatrimestre)
      end

      it "re-renders the 'edit' template" do
        cuatrimestre = Cuatrimestre.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cuatrimestre.any_instance.stub(:save).and_return(false)
        put :update, {:id => cuatrimestre.to_param, :cuatrimestre => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cuatrimestre" do
      cuatrimestre = Cuatrimestre.create! valid_attributes
      expect {
        delete :destroy, {:id => cuatrimestre.to_param}, valid_session
      }.to change(Cuatrimestre, :count).by(-1)
    end

    it "redirects to the cuatrimestres list" do
      cuatrimestre = Cuatrimestre.create! valid_attributes
      delete :destroy, {:id => cuatrimestre.to_param}, valid_session
      response.should redirect_to(cuatrimestres_url)
    end
  end

end
