require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmpresasController do

  # This should return the minimal set of attributes required to create a valid
  # Empresa. As you add validations to Empresa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmpresasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all empresas as @empresas" do
      empresa = Empresa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:empresas).should eq([empresa])
    end
  end

  describe "GET show" do
    it "assigns the requested empresa as @empresa" do
      empresa = Empresa.create! valid_attributes
      get :show, {:id => empresa.to_param}, valid_session
      assigns(:empresa).should eq(empresa)
    end
  end

  describe "GET new" do
    it "assigns a new empresa as @empresa" do
      get :new, {}, valid_session
      assigns(:empresa).should be_a_new(Empresa)
    end
  end

  describe "GET edit" do
    it "assigns the requested empresa as @empresa" do
      empresa = Empresa.create! valid_attributes
      get :edit, {:id => empresa.to_param}, valid_session
      assigns(:empresa).should eq(empresa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Empresa" do
        expect {
          post :create, {:empresa => valid_attributes}, valid_session
        }.to change(Empresa, :count).by(1)
      end

      it "assigns a newly created empresa as @empresa" do
        post :create, {:empresa => valid_attributes}, valid_session
        assigns(:empresa).should be_a(Empresa)
        assigns(:empresa).should be_persisted
      end

      it "redirects to the created empresa" do
        post :create, {:empresa => valid_attributes}, valid_session
        response.should redirect_to(Empresa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved empresa as @empresa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Empresa.any_instance.stub(:save).and_return(false)
        post :create, {:empresa => { "nombre" => "invalid value" }}, valid_session
        assigns(:empresa).should be_a_new(Empresa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Empresa.any_instance.stub(:save).and_return(false)
        post :create, {:empresa => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested empresa" do
        empresa = Empresa.create! valid_attributes
        # Assuming there are no other empresas in the database, this
        # specifies that the Empresa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Empresa.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => empresa.to_param, :empresa => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested empresa as @empresa" do
        empresa = Empresa.create! valid_attributes
        put :update, {:id => empresa.to_param, :empresa => valid_attributes}, valid_session
        assigns(:empresa).should eq(empresa)
      end

      it "redirects to the empresa" do
        empresa = Empresa.create! valid_attributes
        put :update, {:id => empresa.to_param, :empresa => valid_attributes}, valid_session
        response.should redirect_to(empresa)
      end
    end

    describe "with invalid params" do
      it "assigns the empresa as @empresa" do
        empresa = Empresa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Empresa.any_instance.stub(:save).and_return(false)
        put :update, {:id => empresa.to_param, :empresa => { "nombre" => "invalid value" }}, valid_session
        assigns(:empresa).should eq(empresa)
      end

      it "re-renders the 'edit' template" do
        empresa = Empresa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Empresa.any_instance.stub(:save).and_return(false)
        put :update, {:id => empresa.to_param, :empresa => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested empresa" do
      empresa = Empresa.create! valid_attributes
      expect {
        delete :destroy, {:id => empresa.to_param}, valid_session
      }.to change(Empresa, :count).by(-1)
    end

    it "redirects to the empresas list" do
      empresa = Empresa.create! valid_attributes
      delete :destroy, {:id => empresa.to_param}, valid_session
      response.should redirect_to(empresas_url)
    end
  end

end
