require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EncuestasController do

  # This should return the minimal set of attributes required to create a valid
  # Encuesta. As you add validations to Encuesta, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EncuestasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all encuestas as @encuestas" do
      encuesta = Encuesta.create! valid_attributes
      get :index, {}, valid_session
      assigns(:encuestas).should eq([encuesta])
    end
  end

  describe "GET show" do
    it "assigns the requested encuesta as @encuesta" do
      encuesta = Encuesta.create! valid_attributes
      get :show, {:id => encuesta.to_param}, valid_session
      assigns(:encuesta).should eq(encuesta)
    end
  end

  describe "GET new" do
    it "assigns a new encuesta as @encuesta" do
      get :new, {}, valid_session
      assigns(:encuesta).should be_a_new(Encuesta)
    end
  end

  describe "GET edit" do
    it "assigns the requested encuesta as @encuesta" do
      encuesta = Encuesta.create! valid_attributes
      get :edit, {:id => encuesta.to_param}, valid_session
      assigns(:encuesta).should eq(encuesta)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Encuesta" do
        expect {
          post :create, {:encuesta => valid_attributes}, valid_session
        }.to change(Encuesta, :count).by(1)
      end

      it "assigns a newly created encuesta as @encuesta" do
        post :create, {:encuesta => valid_attributes}, valid_session
        assigns(:encuesta).should be_a(Encuesta)
        assigns(:encuesta).should be_persisted
      end

      it "redirects to the created encuesta" do
        post :create, {:encuesta => valid_attributes}, valid_session
        response.should redirect_to(Encuesta.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved encuesta as @encuesta" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encuesta.any_instance.stub(:save).and_return(false)
        post :create, {:encuesta => { "nombre" => "invalid value" }}, valid_session
        assigns(:encuesta).should be_a_new(Encuesta)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encuesta.any_instance.stub(:save).and_return(false)
        post :create, {:encuesta => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested encuesta" do
        encuesta = Encuesta.create! valid_attributes
        # Assuming there are no other encuestas in the database, this
        # specifies that the Encuesta created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Encuesta.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => encuesta.to_param, :encuesta => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested encuesta as @encuesta" do
        encuesta = Encuesta.create! valid_attributes
        put :update, {:id => encuesta.to_param, :encuesta => valid_attributes}, valid_session
        assigns(:encuesta).should eq(encuesta)
      end

      it "redirects to the encuesta" do
        encuesta = Encuesta.create! valid_attributes
        put :update, {:id => encuesta.to_param, :encuesta => valid_attributes}, valid_session
        response.should redirect_to(encuesta)
      end
    end

    describe "with invalid params" do
      it "assigns the encuesta as @encuesta" do
        encuesta = Encuesta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encuesta.any_instance.stub(:save).and_return(false)
        put :update, {:id => encuesta.to_param, :encuesta => { "nombre" => "invalid value" }}, valid_session
        assigns(:encuesta).should eq(encuesta)
      end

      it "re-renders the 'edit' template" do
        encuesta = Encuesta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encuesta.any_instance.stub(:save).and_return(false)
        put :update, {:id => encuesta.to_param, :encuesta => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested encuesta" do
      encuesta = Encuesta.create! valid_attributes
      expect {
        delete :destroy, {:id => encuesta.to_param}, valid_session
      }.to change(Encuesta, :count).by(-1)
    end

    it "redirects to the encuestas list" do
      encuesta = Encuesta.create! valid_attributes
      delete :destroy, {:id => encuesta.to_param}, valid_session
      response.should redirect_to(encuestas_url)
    end
  end

end
