require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IndicadoresController do

  # This should return the minimal set of attributes required to create a valid
  # Indicadore. As you add validations to Indicadore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IndicadoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all indicadores as @indicadores" do
      indicadore = Indicadore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:indicadores).should eq([indicadore])
    end
  end

  describe "GET show" do
    it "assigns the requested indicadore as @indicadore" do
      indicadore = Indicadore.create! valid_attributes
      get :show, {:id => indicadore.to_param}, valid_session
      assigns(:indicadore).should eq(indicadore)
    end
  end

  describe "GET new" do
    it "assigns a new indicadore as @indicadore" do
      get :new, {}, valid_session
      assigns(:indicadore).should be_a_new(Indicadore)
    end
  end

  describe "GET edit" do
    it "assigns the requested indicadore as @indicadore" do
      indicadore = Indicadore.create! valid_attributes
      get :edit, {:id => indicadore.to_param}, valid_session
      assigns(:indicadore).should eq(indicadore)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Indicadore" do
        expect {
          post :create, {:indicadore => valid_attributes}, valid_session
        }.to change(Indicadore, :count).by(1)
      end

      it "assigns a newly created indicadore as @indicadore" do
        post :create, {:indicadore => valid_attributes}, valid_session
        assigns(:indicadore).should be_a(Indicadore)
        assigns(:indicadore).should be_persisted
      end

      it "redirects to the created indicadore" do
        post :create, {:indicadore => valid_attributes}, valid_session
        response.should redirect_to(Indicadore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved indicadore as @indicadore" do
        # Trigger the behavior that occurs when invalid params are submitted
        Indicadore.any_instance.stub(:save).and_return(false)
        post :create, {:indicadore => {  }}, valid_session
        assigns(:indicadore).should be_a_new(Indicadore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Indicadore.any_instance.stub(:save).and_return(false)
        post :create, {:indicadore => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested indicadore" do
        indicadore = Indicadore.create! valid_attributes
        # Assuming there are no other indicadores in the database, this
        # specifies that the Indicadore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Indicadore.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => indicadore.to_param, :indicadore => { "these" => "params" }}, valid_session
      end

      it "assigns the requested indicadore as @indicadore" do
        indicadore = Indicadore.create! valid_attributes
        put :update, {:id => indicadore.to_param, :indicadore => valid_attributes}, valid_session
        assigns(:indicadore).should eq(indicadore)
      end

      it "redirects to the indicadore" do
        indicadore = Indicadore.create! valid_attributes
        put :update, {:id => indicadore.to_param, :indicadore => valid_attributes}, valid_session
        response.should redirect_to(indicadore)
      end
    end

    describe "with invalid params" do
      it "assigns the indicadore as @indicadore" do
        indicadore = Indicadore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Indicadore.any_instance.stub(:save).and_return(false)
        put :update, {:id => indicadore.to_param, :indicadore => {  }}, valid_session
        assigns(:indicadore).should eq(indicadore)
      end

      it "re-renders the 'edit' template" do
        indicadore = Indicadore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Indicadore.any_instance.stub(:save).and_return(false)
        put :update, {:id => indicadore.to_param, :indicadore => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested indicadore" do
      indicadore = Indicadore.create! valid_attributes
      expect {
        delete :destroy, {:id => indicadore.to_param}, valid_session
      }.to change(Indicadore, :count).by(-1)
    end

    it "redirects to the indicadores list" do
      indicadore = Indicadore.create! valid_attributes
      delete :destroy, {:id => indicadore.to_param}, valid_session
      response.should redirect_to(indicadores_url)
    end
  end

end
