require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LibrosController do

  # This should return the minimal set of attributes required to create a valid
  # Libro. As you add validations to Libro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LibrosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all libros as @libros" do
      libro = Libro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:libros).should eq([libro])
    end
  end

  describe "GET show" do
    it "assigns the requested libro as @libro" do
      libro = Libro.create! valid_attributes
      get :show, {:id => libro.to_param}, valid_session
      assigns(:libro).should eq(libro)
    end
  end

  describe "GET new" do
    it "assigns a new libro as @libro" do
      get :new, {}, valid_session
      assigns(:libro).should be_a_new(Libro)
    end
  end

  describe "GET edit" do
    it "assigns the requested libro as @libro" do
      libro = Libro.create! valid_attributes
      get :edit, {:id => libro.to_param}, valid_session
      assigns(:libro).should eq(libro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Libro" do
        expect {
          post :create, {:libro => valid_attributes}, valid_session
        }.to change(Libro, :count).by(1)
      end

      it "assigns a newly created libro as @libro" do
        post :create, {:libro => valid_attributes}, valid_session
        assigns(:libro).should be_a(Libro)
        assigns(:libro).should be_persisted
      end

      it "redirects to the created libro" do
        post :create, {:libro => valid_attributes}, valid_session
        response.should redirect_to(Libro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved libro as @libro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Libro.any_instance.stub(:save).and_return(false)
        post :create, {:libro => { "nombre" => "invalid value" }}, valid_session
        assigns(:libro).should be_a_new(Libro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Libro.any_instance.stub(:save).and_return(false)
        post :create, {:libro => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested libro" do
        libro = Libro.create! valid_attributes
        # Assuming there are no other libros in the database, this
        # specifies that the Libro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Libro.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => libro.to_param, :libro => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested libro as @libro" do
        libro = Libro.create! valid_attributes
        put :update, {:id => libro.to_param, :libro => valid_attributes}, valid_session
        assigns(:libro).should eq(libro)
      end

      it "redirects to the libro" do
        libro = Libro.create! valid_attributes
        put :update, {:id => libro.to_param, :libro => valid_attributes}, valid_session
        response.should redirect_to(libro)
      end
    end

    describe "with invalid params" do
      it "assigns the libro as @libro" do
        libro = Libro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Libro.any_instance.stub(:save).and_return(false)
        put :update, {:id => libro.to_param, :libro => { "nombre" => "invalid value" }}, valid_session
        assigns(:libro).should eq(libro)
      end

      it "re-renders the 'edit' template" do
        libro = Libro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Libro.any_instance.stub(:save).and_return(false)
        put :update, {:id => libro.to_param, :libro => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested libro" do
      libro = Libro.create! valid_attributes
      expect {
        delete :destroy, {:id => libro.to_param}, valid_session
      }.to change(Libro, :count).by(-1)
    end

    it "redirects to the libros list" do
      libro = Libro.create! valid_attributes
      delete :destroy, {:id => libro.to_param}, valid_session
      response.should redirect_to(libros_url)
    end
  end

end
