require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParcialesController do

  # This should return the minimal set of attributes required to create a valid
  # Parcial. As you add validations to Parcial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParcialesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all parciales as @parciales" do
      parcial = Parcial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:parciales).should eq([parcial])
    end
  end

  describe "GET show" do
    it "assigns the requested parcial as @parcial" do
      parcial = Parcial.create! valid_attributes
      get :show, {:id => parcial.to_param}, valid_session
      assigns(:parcial).should eq(parcial)
    end
  end

  describe "GET new" do
    it "assigns a new parcial as @parcial" do
      get :new, {}, valid_session
      assigns(:parcial).should be_a_new(Parcial)
    end
  end

  describe "GET edit" do
    it "assigns the requested parcial as @parcial" do
      parcial = Parcial.create! valid_attributes
      get :edit, {:id => parcial.to_param}, valid_session
      assigns(:parcial).should eq(parcial)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Parcial" do
        expect {
          post :create, {:parcial => valid_attributes}, valid_session
        }.to change(Parcial, :count).by(1)
      end

      it "assigns a newly created parcial as @parcial" do
        post :create, {:parcial => valid_attributes}, valid_session
        assigns(:parcial).should be_a(Parcial)
        assigns(:parcial).should be_persisted
      end

      it "redirects to the created parcial" do
        post :create, {:parcial => valid_attributes}, valid_session
        response.should redirect_to(Parcial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved parcial as @parcial" do
        # Trigger the behavior that occurs when invalid params are submitted
        Parcial.any_instance.stub(:save).and_return(false)
        post :create, {:parcial => { "nombre" => "invalid value" }}, valid_session
        assigns(:parcial).should be_a_new(Parcial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Parcial.any_instance.stub(:save).and_return(false)
        post :create, {:parcial => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested parcial" do
        parcial = Parcial.create! valid_attributes
        # Assuming there are no other parciales in the database, this
        # specifies that the Parcial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Parcial.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => parcial.to_param, :parcial => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested parcial as @parcial" do
        parcial = Parcial.create! valid_attributes
        put :update, {:id => parcial.to_param, :parcial => valid_attributes}, valid_session
        assigns(:parcial).should eq(parcial)
      end

      it "redirects to the parcial" do
        parcial = Parcial.create! valid_attributes
        put :update, {:id => parcial.to_param, :parcial => valid_attributes}, valid_session
        response.should redirect_to(parcial)
      end
    end

    describe "with invalid params" do
      it "assigns the parcial as @parcial" do
        parcial = Parcial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Parcial.any_instance.stub(:save).and_return(false)
        put :update, {:id => parcial.to_param, :parcial => { "nombre" => "invalid value" }}, valid_session
        assigns(:parcial).should eq(parcial)
      end

      it "re-renders the 'edit' template" do
        parcial = Parcial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Parcial.any_instance.stub(:save).and_return(false)
        put :update, {:id => parcial.to_param, :parcial => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested parcial" do
      parcial = Parcial.create! valid_attributes
      expect {
        delete :destroy, {:id => parcial.to_param}, valid_session
      }.to change(Parcial, :count).by(-1)
    end

    it "redirects to the parciales list" do
      parcial = Parcial.create! valid_attributes
      delete :destroy, {:id => parcial.to_param}, valid_session
      response.should redirect_to(parciales_url)
    end
  end

end
