require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RubrosController do

  # This should return the minimal set of attributes required to create a valid
  # Rubro. As you add validations to Rubro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sb1" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RubrosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rubros as @rubros" do
      rubro = Rubro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rubros).should eq([rubro])
    end
  end

  describe "GET show" do
    it "assigns the requested rubro as @rubro" do
      rubro = Rubro.create! valid_attributes
      get :show, {:id => rubro.to_param}, valid_session
      assigns(:rubro).should eq(rubro)
    end
  end

  describe "GET new" do
    it "assigns a new rubro as @rubro" do
      get :new, {}, valid_session
      assigns(:rubro).should be_a_new(Rubro)
    end
  end

  describe "GET edit" do
    it "assigns the requested rubro as @rubro" do
      rubro = Rubro.create! valid_attributes
      get :edit, {:id => rubro.to_param}, valid_session
      assigns(:rubro).should eq(rubro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rubro" do
        expect {
          post :create, {:rubro => valid_attributes}, valid_session
        }.to change(Rubro, :count).by(1)
      end

      it "assigns a newly created rubro as @rubro" do
        post :create, {:rubro => valid_attributes}, valid_session
        assigns(:rubro).should be_a(Rubro)
        assigns(:rubro).should be_persisted
      end

      it "redirects to the created rubro" do
        post :create, {:rubro => valid_attributes}, valid_session
        response.should redirect_to(Rubro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rubro as @rubro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rubro.any_instance.stub(:save).and_return(false)
        post :create, {:rubro => { "sb1" => "invalid value" }}, valid_session
        assigns(:rubro).should be_a_new(Rubro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rubro.any_instance.stub(:save).and_return(false)
        post :create, {:rubro => { "sb1" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rubro" do
        rubro = Rubro.create! valid_attributes
        # Assuming there are no other rubros in the database, this
        # specifies that the Rubro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rubro.any_instance.should_receive(:update).with({ "sb1" => "1" })
        put :update, {:id => rubro.to_param, :rubro => { "sb1" => "1" }}, valid_session
      end

      it "assigns the requested rubro as @rubro" do
        rubro = Rubro.create! valid_attributes
        put :update, {:id => rubro.to_param, :rubro => valid_attributes}, valid_session
        assigns(:rubro).should eq(rubro)
      end

      it "redirects to the rubro" do
        rubro = Rubro.create! valid_attributes
        put :update, {:id => rubro.to_param, :rubro => valid_attributes}, valid_session
        response.should redirect_to(rubro)
      end
    end

    describe "with invalid params" do
      it "assigns the rubro as @rubro" do
        rubro = Rubro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rubro.any_instance.stub(:save).and_return(false)
        put :update, {:id => rubro.to_param, :rubro => { "sb1" => "invalid value" }}, valid_session
        assigns(:rubro).should eq(rubro)
      end

      it "re-renders the 'edit' template" do
        rubro = Rubro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rubro.any_instance.stub(:save).and_return(false)
        put :update, {:id => rubro.to_param, :rubro => { "sb1" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rubro" do
      rubro = Rubro.create! valid_attributes
      expect {
        delete :destroy, {:id => rubro.to_param}, valid_session
      }.to change(Rubro, :count).by(-1)
    end

    it "redirects to the rubros list" do
      rubro = Rubro.create! valid_attributes
      delete :destroy, {:id => rubro.to_param}, valid_session
      response.should redirect_to(rubros_url)
    end
  end

end
