require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SCriteriosController do

  # This should return the minimal set of attributes required to create a valid
  # SCriterio. As you add validations to SCriterio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "porcentaje" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SCriteriosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all s_criterios as @s_criterios" do
      s_criterio = SCriterio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:s_criterios).should eq([s_criterio])
    end
  end

  describe "GET show" do
    it "assigns the requested s_criterio as @s_criterio" do
      s_criterio = SCriterio.create! valid_attributes
      get :show, {:id => s_criterio.to_param}, valid_session
      assigns(:s_criterio).should eq(s_criterio)
    end
  end

  describe "GET new" do
    it "assigns a new s_criterio as @s_criterio" do
      get :new, {}, valid_session
      assigns(:s_criterio).should be_a_new(SCriterio)
    end
  end

  describe "GET edit" do
    it "assigns the requested s_criterio as @s_criterio" do
      s_criterio = SCriterio.create! valid_attributes
      get :edit, {:id => s_criterio.to_param}, valid_session
      assigns(:s_criterio).should eq(s_criterio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SCriterio" do
        expect {
          post :create, {:s_criterio => valid_attributes}, valid_session
        }.to change(SCriterio, :count).by(1)
      end

      it "assigns a newly created s_criterio as @s_criterio" do
        post :create, {:s_criterio => valid_attributes}, valid_session
        assigns(:s_criterio).should be_a(SCriterio)
        assigns(:s_criterio).should be_persisted
      end

      it "redirects to the created s_criterio" do
        post :create, {:s_criterio => valid_attributes}, valid_session
        response.should redirect_to(SCriterio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved s_criterio as @s_criterio" do
        # Trigger the behavior that occurs when invalid params are submitted
        SCriterio.any_instance.stub(:save).and_return(false)
        post :create, {:s_criterio => { "porcentaje" => "invalid value" }}, valid_session
        assigns(:s_criterio).should be_a_new(SCriterio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SCriterio.any_instance.stub(:save).and_return(false)
        post :create, {:s_criterio => { "porcentaje" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested s_criterio" do
        s_criterio = SCriterio.create! valid_attributes
        # Assuming there are no other s_criterios in the database, this
        # specifies that the SCriterio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SCriterio.any_instance.should_receive(:update).with({ "porcentaje" => "1" })
        put :update, {:id => s_criterio.to_param, :s_criterio => { "porcentaje" => "1" }}, valid_session
      end

      it "assigns the requested s_criterio as @s_criterio" do
        s_criterio = SCriterio.create! valid_attributes
        put :update, {:id => s_criterio.to_param, :s_criterio => valid_attributes}, valid_session
        assigns(:s_criterio).should eq(s_criterio)
      end

      it "redirects to the s_criterio" do
        s_criterio = SCriterio.create! valid_attributes
        put :update, {:id => s_criterio.to_param, :s_criterio => valid_attributes}, valid_session
        response.should redirect_to(s_criterio)
      end
    end

    describe "with invalid params" do
      it "assigns the s_criterio as @s_criterio" do
        s_criterio = SCriterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SCriterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => s_criterio.to_param, :s_criterio => { "porcentaje" => "invalid value" }}, valid_session
        assigns(:s_criterio).should eq(s_criterio)
      end

      it "re-renders the 'edit' template" do
        s_criterio = SCriterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SCriterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => s_criterio.to_param, :s_criterio => { "porcentaje" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested s_criterio" do
      s_criterio = SCriterio.create! valid_attributes
      expect {
        delete :destroy, {:id => s_criterio.to_param}, valid_session
      }.to change(SCriterio, :count).by(-1)
    end

    it "redirects to the s_criterios list" do
      s_criterio = SCriterio.create! valid_attributes
      delete :destroy, {:id => s_criterio.to_param}, valid_session
      response.should redirect_to(s_criterios_url)
    end
  end

end
