require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SbCriteriosController do

  # This should return the minimal set of attributes required to create a valid
  # SbCriterio. As you add validations to SbCriterio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SbCriteriosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sb_criterios as @sb_criterios" do
      sb_criterio = SbCriterio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sb_criterios).should eq([sb_criterio])
    end
  end

  describe "GET show" do
    it "assigns the requested sb_criterio as @sb_criterio" do
      sb_criterio = SbCriterio.create! valid_attributes
      get :show, {:id => sb_criterio.to_param}, valid_session
      assigns(:sb_criterio).should eq(sb_criterio)
    end
  end

  describe "GET new" do
    it "assigns a new sb_criterio as @sb_criterio" do
      get :new, {}, valid_session
      assigns(:sb_criterio).should be_a_new(SbCriterio)
    end
  end

  describe "GET edit" do
    it "assigns the requested sb_criterio as @sb_criterio" do
      sb_criterio = SbCriterio.create! valid_attributes
      get :edit, {:id => sb_criterio.to_param}, valid_session
      assigns(:sb_criterio).should eq(sb_criterio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SbCriterio" do
        expect {
          post :create, {:sb_criterio => valid_attributes}, valid_session
        }.to change(SbCriterio, :count).by(1)
      end

      it "assigns a newly created sb_criterio as @sb_criterio" do
        post :create, {:sb_criterio => valid_attributes}, valid_session
        assigns(:sb_criterio).should be_a(SbCriterio)
        assigns(:sb_criterio).should be_persisted
      end

      it "redirects to the created sb_criterio" do
        post :create, {:sb_criterio => valid_attributes}, valid_session
        response.should redirect_to(SbCriterio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sb_criterio as @sb_criterio" do
        # Trigger the behavior that occurs when invalid params are submitted
        SbCriterio.any_instance.stub(:save).and_return(false)
        post :create, {:sb_criterio => { "nombre" => "invalid value" }}, valid_session
        assigns(:sb_criterio).should be_a_new(SbCriterio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SbCriterio.any_instance.stub(:save).and_return(false)
        post :create, {:sb_criterio => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sb_criterio" do
        sb_criterio = SbCriterio.create! valid_attributes
        # Assuming there are no other sb_criterios in the database, this
        # specifies that the SbCriterio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SbCriterio.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => sb_criterio.to_param, :sb_criterio => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested sb_criterio as @sb_criterio" do
        sb_criterio = SbCriterio.create! valid_attributes
        put :update, {:id => sb_criterio.to_param, :sb_criterio => valid_attributes}, valid_session
        assigns(:sb_criterio).should eq(sb_criterio)
      end

      it "redirects to the sb_criterio" do
        sb_criterio = SbCriterio.create! valid_attributes
        put :update, {:id => sb_criterio.to_param, :sb_criterio => valid_attributes}, valid_session
        response.should redirect_to(sb_criterio)
      end
    end

    describe "with invalid params" do
      it "assigns the sb_criterio as @sb_criterio" do
        sb_criterio = SbCriterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SbCriterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => sb_criterio.to_param, :sb_criterio => { "nombre" => "invalid value" }}, valid_session
        assigns(:sb_criterio).should eq(sb_criterio)
      end

      it "re-renders the 'edit' template" do
        sb_criterio = SbCriterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SbCriterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => sb_criterio.to_param, :sb_criterio => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sb_criterio" do
      sb_criterio = SbCriterio.create! valid_attributes
      expect {
        delete :destroy, {:id => sb_criterio.to_param}, valid_session
      }.to change(SbCriterio, :count).by(-1)
    end

    it "redirects to the sb_criterios list" do
      sb_criterio = SbCriterio.create! valid_attributes
      delete :destroy, {:id => sb_criterio.to_param}, valid_session
      response.should redirect_to(sb_criterios_url)
    end
  end

end
