require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShCriteriosController do

  # This should return the minimal set of attributes required to create a valid
  # ShCriterio. As you add validations to ShCriterio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShCriteriosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sh_criterios as @sh_criterios" do
      sh_criterio = ShCriterio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sh_criterios).should eq([sh_criterio])
    end
  end

  describe "GET show" do
    it "assigns the requested sh_criterio as @sh_criterio" do
      sh_criterio = ShCriterio.create! valid_attributes
      get :show, {:id => sh_criterio.to_param}, valid_session
      assigns(:sh_criterio).should eq(sh_criterio)
    end
  end

  describe "GET new" do
    it "assigns a new sh_criterio as @sh_criterio" do
      get :new, {}, valid_session
      assigns(:sh_criterio).should be_a_new(ShCriterio)
    end
  end

  describe "GET edit" do
    it "assigns the requested sh_criterio as @sh_criterio" do
      sh_criterio = ShCriterio.create! valid_attributes
      get :edit, {:id => sh_criterio.to_param}, valid_session
      assigns(:sh_criterio).should eq(sh_criterio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShCriterio" do
        expect {
          post :create, {:sh_criterio => valid_attributes}, valid_session
        }.to change(ShCriterio, :count).by(1)
      end

      it "assigns a newly created sh_criterio as @sh_criterio" do
        post :create, {:sh_criterio => valid_attributes}, valid_session
        assigns(:sh_criterio).should be_a(ShCriterio)
        assigns(:sh_criterio).should be_persisted
      end

      it "redirects to the created sh_criterio" do
        post :create, {:sh_criterio => valid_attributes}, valid_session
        response.should redirect_to(ShCriterio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sh_criterio as @sh_criterio" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShCriterio.any_instance.stub(:save).and_return(false)
        post :create, {:sh_criterio => { "nombre" => "invalid value" }}, valid_session
        assigns(:sh_criterio).should be_a_new(ShCriterio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShCriterio.any_instance.stub(:save).and_return(false)
        post :create, {:sh_criterio => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sh_criterio" do
        sh_criterio = ShCriterio.create! valid_attributes
        # Assuming there are no other sh_criterios in the database, this
        # specifies that the ShCriterio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShCriterio.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => sh_criterio.to_param, :sh_criterio => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested sh_criterio as @sh_criterio" do
        sh_criterio = ShCriterio.create! valid_attributes
        put :update, {:id => sh_criterio.to_param, :sh_criterio => valid_attributes}, valid_session
        assigns(:sh_criterio).should eq(sh_criterio)
      end

      it "redirects to the sh_criterio" do
        sh_criterio = ShCriterio.create! valid_attributes
        put :update, {:id => sh_criterio.to_param, :sh_criterio => valid_attributes}, valid_session
        response.should redirect_to(sh_criterio)
      end
    end

    describe "with invalid params" do
      it "assigns the sh_criterio as @sh_criterio" do
        sh_criterio = ShCriterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShCriterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => sh_criterio.to_param, :sh_criterio => { "nombre" => "invalid value" }}, valid_session
        assigns(:sh_criterio).should eq(sh_criterio)
      end

      it "re-renders the 'edit' template" do
        sh_criterio = ShCriterio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShCriterio.any_instance.stub(:save).and_return(false)
        put :update, {:id => sh_criterio.to_param, :sh_criterio => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sh_criterio" do
      sh_criterio = ShCriterio.create! valid_attributes
      expect {
        delete :destroy, {:id => sh_criterio.to_param}, valid_session
      }.to change(ShCriterio, :count).by(-1)
    end

    it "redirects to the sh_criterios list" do
      sh_criterio = ShCriterio.create! valid_attributes
      delete :destroy, {:id => sh_criterio.to_param}, valid_session
      response.should redirect_to(sh_criterios_url)
    end
  end

end
