require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TutorGruposController do

  # This should return the minimal set of attributes required to create a valid
  # TutorGrupo. As you add validations to TutorGrupo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "grupo_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TutorGruposController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tutor_grupos as @tutor_grupos" do
      tutor_grupo = TutorGrupo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tutor_grupos).should eq([tutor_grupo])
    end
  end

  describe "GET show" do
    it "assigns the requested tutor_grupo as @tutor_grupo" do
      tutor_grupo = TutorGrupo.create! valid_attributes
      get :show, {:id => tutor_grupo.to_param}, valid_session
      assigns(:tutor_grupo).should eq(tutor_grupo)
    end
  end

  describe "GET new" do
    it "assigns a new tutor_grupo as @tutor_grupo" do
      get :new, {}, valid_session
      assigns(:tutor_grupo).should be_a_new(TutorGrupo)
    end
  end

  describe "GET edit" do
    it "assigns the requested tutor_grupo as @tutor_grupo" do
      tutor_grupo = TutorGrupo.create! valid_attributes
      get :edit, {:id => tutor_grupo.to_param}, valid_session
      assigns(:tutor_grupo).should eq(tutor_grupo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TutorGrupo" do
        expect {
          post :create, {:tutor_grupo => valid_attributes}, valid_session
        }.to change(TutorGrupo, :count).by(1)
      end

      it "assigns a newly created tutor_grupo as @tutor_grupo" do
        post :create, {:tutor_grupo => valid_attributes}, valid_session
        assigns(:tutor_grupo).should be_a(TutorGrupo)
        assigns(:tutor_grupo).should be_persisted
      end

      it "redirects to the created tutor_grupo" do
        post :create, {:tutor_grupo => valid_attributes}, valid_session
        response.should redirect_to(TutorGrupo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tutor_grupo as @tutor_grupo" do
        # Trigger the behavior that occurs when invalid params are submitted
        TutorGrupo.any_instance.stub(:save).and_return(false)
        post :create, {:tutor_grupo => { "grupo_id" => "invalid value" }}, valid_session
        assigns(:tutor_grupo).should be_a_new(TutorGrupo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TutorGrupo.any_instance.stub(:save).and_return(false)
        post :create, {:tutor_grupo => { "grupo_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tutor_grupo" do
        tutor_grupo = TutorGrupo.create! valid_attributes
        # Assuming there are no other tutor_grupos in the database, this
        # specifies that the TutorGrupo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TutorGrupo.any_instance.should_receive(:update).with({ "grupo_id" => "1" })
        put :update, {:id => tutor_grupo.to_param, :tutor_grupo => { "grupo_id" => "1" }}, valid_session
      end

      it "assigns the requested tutor_grupo as @tutor_grupo" do
        tutor_grupo = TutorGrupo.create! valid_attributes
        put :update, {:id => tutor_grupo.to_param, :tutor_grupo => valid_attributes}, valid_session
        assigns(:tutor_grupo).should eq(tutor_grupo)
      end

      it "redirects to the tutor_grupo" do
        tutor_grupo = TutorGrupo.create! valid_attributes
        put :update, {:id => tutor_grupo.to_param, :tutor_grupo => valid_attributes}, valid_session
        response.should redirect_to(tutor_grupo)
      end
    end

    describe "with invalid params" do
      it "assigns the tutor_grupo as @tutor_grupo" do
        tutor_grupo = TutorGrupo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TutorGrupo.any_instance.stub(:save).and_return(false)
        put :update, {:id => tutor_grupo.to_param, :tutor_grupo => { "grupo_id" => "invalid value" }}, valid_session
        assigns(:tutor_grupo).should eq(tutor_grupo)
      end

      it "re-renders the 'edit' template" do
        tutor_grupo = TutorGrupo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TutorGrupo.any_instance.stub(:save).and_return(false)
        put :update, {:id => tutor_grupo.to_param, :tutor_grupo => { "grupo_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tutor_grupo" do
      tutor_grupo = TutorGrupo.create! valid_attributes
      expect {
        delete :destroy, {:id => tutor_grupo.to_param}, valid_session
      }.to change(TutorGrupo, :count).by(-1)
    end

    it "redirects to the tutor_grupos list" do
      tutor_grupo = TutorGrupo.create! valid_attributes
      delete :destroy, {:id => tutor_grupo.to_param}, valid_session
      response.should redirect_to(tutor_grupos_url)
    end
  end

end
