require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VinculacionesController do

  # This should return the minimal set of attributes required to create a valid
  # Vinculacion. As you add validations to Vinculacion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "carrera_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VinculacionesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vinculaciones as @vinculaciones" do
      vinculacion = Vinculacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vinculaciones).should eq([vinculacion])
    end
  end

  describe "GET show" do
    it "assigns the requested vinculacion as @vinculacion" do
      vinculacion = Vinculacion.create! valid_attributes
      get :show, {:id => vinculacion.to_param}, valid_session
      assigns(:vinculacion).should eq(vinculacion)
    end
  end

  describe "GET new" do
    it "assigns a new vinculacion as @vinculacion" do
      get :new, {}, valid_session
      assigns(:vinculacion).should be_a_new(Vinculacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested vinculacion as @vinculacion" do
      vinculacion = Vinculacion.create! valid_attributes
      get :edit, {:id => vinculacion.to_param}, valid_session
      assigns(:vinculacion).should eq(vinculacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vinculacion" do
        expect {
          post :create, {:vinculacion => valid_attributes}, valid_session
        }.to change(Vinculacion, :count).by(1)
      end

      it "assigns a newly created vinculacion as @vinculacion" do
        post :create, {:vinculacion => valid_attributes}, valid_session
        assigns(:vinculacion).should be_a(Vinculacion)
        assigns(:vinculacion).should be_persisted
      end

      it "redirects to the created vinculacion" do
        post :create, {:vinculacion => valid_attributes}, valid_session
        response.should redirect_to(Vinculacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vinculacion as @vinculacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vinculacion.any_instance.stub(:save).and_return(false)
        post :create, {:vinculacion => { "carrera_id" => "invalid value" }}, valid_session
        assigns(:vinculacion).should be_a_new(Vinculacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vinculacion.any_instance.stub(:save).and_return(false)
        post :create, {:vinculacion => { "carrera_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vinculacion" do
        vinculacion = Vinculacion.create! valid_attributes
        # Assuming there are no other vinculaciones in the database, this
        # specifies that the Vinculacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vinculacion.any_instance.should_receive(:update).with({ "carrera_id" => "1" })
        put :update, {:id => vinculacion.to_param, :vinculacion => { "carrera_id" => "1" }}, valid_session
      end

      it "assigns the requested vinculacion as @vinculacion" do
        vinculacion = Vinculacion.create! valid_attributes
        put :update, {:id => vinculacion.to_param, :vinculacion => valid_attributes}, valid_session
        assigns(:vinculacion).should eq(vinculacion)
      end

      it "redirects to the vinculacion" do
        vinculacion = Vinculacion.create! valid_attributes
        put :update, {:id => vinculacion.to_param, :vinculacion => valid_attributes}, valid_session
        response.should redirect_to(vinculacion)
      end
    end

    describe "with invalid params" do
      it "assigns the vinculacion as @vinculacion" do
        vinculacion = Vinculacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vinculacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => vinculacion.to_param, :vinculacion => { "carrera_id" => "invalid value" }}, valid_session
        assigns(:vinculacion).should eq(vinculacion)
      end

      it "re-renders the 'edit' template" do
        vinculacion = Vinculacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vinculacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => vinculacion.to_param, :vinculacion => { "carrera_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vinculacion" do
      vinculacion = Vinculacion.create! valid_attributes
      expect {
        delete :destroy, {:id => vinculacion.to_param}, valid_session
      }.to change(Vinculacion, :count).by(-1)
    end

    it "redirects to the vinculaciones list" do
      vinculacion = Vinculacion.create! valid_attributes
      delete :destroy, {:id => vinculacion.to_param}, valid_session
      response.should redirect_to(vinculaciones_url)
    end
  end

end
